// mail-vue/src/views/login/SpaceTrail.vue
<template>
  <!-- Warp-speed space trail: contained region, pointer-events-none, z-1 -->
  <div
    class="space-trail-container pointer-events-none"
    aria-hidden="true"
  >
    <canvas ref="trailCanvas" class="space-trail-canvas" />
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';

const trailCanvas = ref(null);
let raf = null;

onMounted(() => {
  const canvas = trailCanvas.value;
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduceMotion) return; // respect accessibility

  // ─── Canvas size tied to container ───────────────────────────────────────
  let W = 0, H = 0;
  const dpr = Math.min(window.devicePixelRatio || 1, 2);

  const resize = () => {
    const rect = canvas.parentElement.getBoundingClientRect();
    W = rect.width;
    H = rect.height;
    canvas.width  = Math.floor(W * dpr);
    canvas.height = Math.floor(H * dpr);
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  };
  resize();

  const ro = new ResizeObserver(resize);
  ro.observe(canvas.parentElement);

  // ─── Color palette ─────────────────────────────────────────────────────
  const COLORS = [
    [168, 85, 247],   // purple
    [99,  102, 241],  // indigo
    [103, 232, 249],  // cyan
    [226, 232, 255],  // star-white
  ];

  // ─── Warp stars ────────────────────────────────────────────────────────
  // Each star flies from a "vanishing point" near the center-right of the
  // contained canvas outward to create a warp-tunnel feel.
  const STAR_COUNT = 120;
  const VX = W * 0.52; // vanishing point X (roughly center-right)
  const VY = H * 0.48; // vanishing point Y

  function makeWarpStar() {
    const angle  = Math.random() * Math.PI * 2;
    const seed   = Math.random() * 0.1 + 0.001; // small initial dist from VP
    const speed  = Math.random() * 3.2 + 0.9;
    const col    = COLORS[Math.floor(Math.random() * COLORS.length)];
    return { angle, dist: seed, maxDist: Math.random() * 0.55 + 0.55, speed, col };
  }

  let warpStars = Array.from({ length: STAR_COUNT }, makeWarpStar);
  // Scatter initial distances so they don't all start at 0
  warpStars.forEach(s => { s.dist = Math.random() * s.maxDist; });

  // ─── Meteors ────────────────────────────────────────────────────────────
  const MAX_METEORS = 5;
  const meteors = [];

  function spawnMeteor() {
    if (meteors.length >= MAX_METEORS) return;
    // Entry from top or left edge
    const fromLeft = Math.random() < 0.5;
    const mx = fromLeft ? 0 : Math.random() * W;
    const my = fromLeft ? Math.random() * H * 0.6 : 0;
    const angle = Math.PI / 4 + (Math.random() - 0.5) * 0.5; // ~45° diagonal
    const speed = Math.random() * 3.5 + 2.5;
    const length = Math.random() * 90 + 60;
    const col = COLORS[Math.floor(Math.random() * 3)]; // purple/indigo/cyan
    meteors.push({ x: mx, y: my, angle, speed, length, alpha: 1, col, age: 0 });
  }

  // Stagger initial meteor spawns
  for (let i = 0; i < 2; i++) spawnMeteor();

  // ─── Asteroid debris ────────────────────────────────────────────────────
  const DEBRIS_COUNT = 18;
  function makeDebris() {
    return {
      x:  Math.random() * W,
      y:  Math.random() * H,
      vx: (Math.random() - 0.5) * 0.6,
      vy: (Math.random() - 0.5) * 0.6,
      r:  Math.random() * 1.8 + 0.4,
      alpha: Math.random() * 0.4 + 0.15,
      phase: Math.random() * Math.PI * 2,
      speed: Math.random() * 0.8 + 0.3,
    };
  }
  const debris = Array.from({ length: DEBRIS_COUNT }, makeDebris);

  // ─── Render loop ────────────────────────────────────────────────────────
  const start = performance.now();
  let lastMeteorSpawn = 0;

  const render = (now) => {
    const t = (now - start) / 1000;
    ctx.clearRect(0, 0, W, H);

    // Fade trail (deep space background for contained area)
    ctx.fillStyle = 'rgba(5, 6, 15, 0.18)';
    ctx.fillRect(0, 0, W, H);

    const vx = W * 0.52;
    const vy = H * 0.48;

    // ── Warp stars ─────────────────────────────────────────────────────
    ctx.globalCompositeOperation = 'lighter';
    for (const s of warpStars) {
      // Grow dist from vanishing point
      s.dist += s.speed * 0.004;

      const normDist = s.dist / s.maxDist; // 0→1
      const r = normDist * Math.min(W, H) * 0.72; // actual radius from VP

      const x = vx + Math.cos(s.angle) * r;
      const y = vy + Math.sin(s.angle) * r;

      // Streak length grows with speed (deeper into warp)
      const streakLen = normDist * normDist * 28 + 1;
      const prevX = x - Math.cos(s.angle) * streakLen;
      const prevY = y - Math.sin(s.angle) * streakLen;

      const a = Math.min(normDist * normDist * 0.9, 0.85);
      const [cr, cg, cb] = s.col;

      const grad = ctx.createLinearGradient(prevX, prevY, x, y);
      grad.addColorStop(0, `rgba(${cr},${cg},${cb},0)`);
      grad.addColorStop(1, `rgba(${cr},${cg},${cb},${a})`);

      ctx.beginPath();
      ctx.moveTo(prevX, prevY);
      ctx.lineTo(x, y);
      ctx.strokeStyle = grad;
      ctx.lineWidth   = normDist * 1.6 + 0.4;
      ctx.stroke();

      // Reset star when it exits the canvas
      if (x < -10 || x > W + 10 || y < -10 || y > H + 10 || s.dist >= s.maxDist) {
        Object.assign(s, makeWarpStar());
        s.dist = 0;
      }
    }
    ctx.globalCompositeOperation = 'source-over';

    // ── Meteors ────────────────────────────────────────────────────────
    if (now - lastMeteorSpawn > 1800 + Math.random() * 2200) {
      spawnMeteor();
      lastMeteorSpawn = now;
    }

    for (let i = meteors.length - 1; i >= 0; i--) {
      const m = meteors[i];
      m.x   += Math.cos(m.angle) * m.speed;
      m.y   += Math.sin(m.angle) * m.speed;
      m.age += 1;

      // Fade out near edge
      const edgeDist = Math.min(m.x, m.y, W - m.x, H - m.y);
      m.alpha = Math.min(1, edgeDist / 60);

      // Head of meteor
      const tailX = m.x - Math.cos(m.angle) * m.length;
      const tailY = m.y - Math.sin(m.angle) * m.length;

      ctx.globalCompositeOperation = 'lighter';
      const [mr, mg, mb] = m.col;
      const mGrad = ctx.createLinearGradient(tailX, tailY, m.x, m.y);
      mGrad.addColorStop(0, `rgba(${mr},${mg},${mb},0)`);
      mGrad.addColorStop(0.7, `rgba(${mr},${mg},${mb},${m.alpha * 0.55})`);
      mGrad.addColorStop(1,   `rgba(255,255,255,${m.alpha * 0.95})`);
      ctx.beginPath();
      ctx.moveTo(tailX, tailY);
      ctx.lineTo(m.x, m.y);
      ctx.strokeStyle = mGrad;
      ctx.lineWidth = 1.6;
      ctx.stroke();
      ctx.globalCompositeOperation = 'source-over';

      // Glow head dot
      ctx.beginPath();
      ctx.arc(m.x, m.y, 1.8, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(255,255,255,${m.alpha * 0.95})`;
      ctx.fill();

      // Remove if out of bounds
      if (m.x > W + m.length || m.y > H + m.length || m.x < -m.length || m.y < -m.length) {
        meteors.splice(i, 1);
      }
    }

    // ── Floating debris (tiny drifting particles) ─────────────────────
    for (const d of debris) {
      d.x += d.vx;
      d.y += d.vy;
      // Wrap around canvas edges
      if (d.x < 0) d.x = W;
      if (d.x > W) d.x = 0;
      if (d.y < 0) d.y = H;
      if (d.y > H) d.y = 0;

      const pulse = d.alpha * (0.7 + Math.sin(t * d.speed + d.phase) * 0.3);
      ctx.beginPath();
      ctx.arc(d.x, d.y, d.r, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(200, 210, 255, ${pulse})`;
      ctx.fill();
    }

    raf = requestAnimationFrame(render);
  };

  raf = requestAnimationFrame(render);

  onUnmounted(() => {
    cancelAnimationFrame(raf);
    ro.disconnect();
  });
});
</script>

<style scoped>
.space-trail-container {
  position: absolute;
  /* Bottom-left quadrant — local, contained visual area */
  left: 0;
  bottom: 0;
  width: 52vw;
  height: 58vh;
  z-index: 2; /* above main canvas bg (z-index 1), below form wrapper (z-10) */
  overflow: hidden;
  /* Vignette mask — fades edges so it blends seamlessly */
  -webkit-mask-image:
    radial-gradient(ellipse 85% 85% at 20% 80%, black 0%, transparent 100%);
  mask-image:
    radial-gradient(ellipse 85% 85% at 20% 80%, black 0%, transparent 100%);
}

.space-trail-canvas {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
}

@media (max-width: 767px) {
  .space-trail-container {
    width: 100vw;
    height: 45vh;
    -webkit-mask-image:
      radial-gradient(ellipse 90% 80% at 50% 100%, black 0%, transparent 100%);
    mask-image:
      radial-gradient(ellipse 90% 80% at 50% 100%, black 0%, transparent 100%);
  }
}
</style>

// temp_login_ui/src/app/components/epomail/SpaceTrail.tsx
import { useEffect, useRef } from "react";

const PURPLE: [number, number, number] = [168, 85, 247];
const INDIGO: [number, number, number] = [99, 102, 241];
const CYAN: [number, number, number] = [103, 232, 249];

interface WarpStar {
  x: number;
  y: number;
  z: number;
  speed: number;
  col: [number, number, number];
  angle: number;
}

interface Comet {
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  maxLife: number;
  size: number;
  col: [number, number, number];
}

interface Asteroid {
  x: number;
  y: number;
  vx: number;
  vy: number;
  rot: number;
  vRot: number;
  size: number;
  pts: number[];
}

interface Dust {
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  maxLife: number;
}

export function SpaceTrail() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d", { alpha: true });
    if (!ctx) return;

    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduceMotion) return;

    let W = 0;
    let H = 0;
    let dpr = 1;

    let warpStars: WarpStar[] = [];
    let comets: Comet[] = [];
    let asteroids: Asteroid[] = [];
    let dusts: Dust[] = [];

    const initEntities = () => {
      // 180 warp stars
      warpStars = Array.from({ length: 180 }, () => {
        const angle = Math.random() * Math.PI * 2;
        return {
          x: (Math.random() - 0.5) * W,
          y: (Math.random() - 0.5) * H,
          z: Math.random() * 1000 + 100,
          speed: Math.random() * 15 + 2,
          col: Math.random() > 0.5 ? CYAN : INDIGO,
          angle,
        };
      });

      // 4 comets
      comets = Array.from({ length: 4 }, spawnComet);

      // 12 asteroids
      asteroids = Array.from({ length: 12 }, () => spawnAsteroid(true));

      // 60 dust particles
      dusts = Array.from({ length: 60 }, spawnDust);
    };

    const spawnComet = (): Comet => {
      const isHorizontal = Math.random() > 0.5;
      const vx = isHorizontal ? (Math.random() * 25 + 15) * (Math.random() > 0.5 ? 1 : -1) : (Math.random() - 0.5) * 10;
      const vy = !isHorizontal ? (Math.random() * 25 + 15) * (Math.random() > 0.5 ? 1 : -1) : (Math.random() - 0.5) * 10;
      return {
        x: Math.random() * W,
        y: Math.random() * H,
        vx,
        vy,
        life: 0,
        maxLife: Math.random() * 40 + 20,
        size: Math.random() * 3 + 2,
        col: Math.random() > 0.5 ? PURPLE : CYAN,
      };
    };

    const spawnAsteroid = (initial = false): Asteroid => {
      const pts = Array.from({ length: 7 }, () => Math.random() * 0.4 + 0.6);
      return {
        x: initial ? Math.random() * W : (Math.random() > 0.5 ? -50 : W + 50),
        y: initial ? Math.random() * H : Math.random() * H,
        vx: (Math.random() - 0.5) * 6,
        vy: (Math.random() - 0.5) * 6,
        rot: Math.random() * Math.PI * 2,
        vRot: (Math.random() - 0.5) * 0.15,
        size: Math.random() * 15 + 5,
        pts,
      };
    };

    const spawnDust = (): Dust => {
      return {
        x: Math.random() * W,
        y: Math.random() * H,
        vx: (Math.random() - 0.5) * 15,
        vy: (Math.random() - 0.5) * 15,
        life: 0,
        maxLife: Math.random() * 30 + 10,
      };
    };

    const resizeObserver = new ResizeObserver((entries) => {
      for (const entry of entries) {
        const { width, height } = entry.contentRect;
        dpr = Math.min(window.devicePixelRatio || 1, 2);
        W = width;
        H = height;
        canvas.width = W * dpr;
        canvas.height = H * dpr;
        ctx.scale(dpr, dpr);
        initEntities();
      }
    });

    if (canvas.parentElement) {
      resizeObserver.observe(canvas.parentElement);
    }

    let raf = 0;

    const render = () => {
      ctx.clearRect(0, 0, W, H);

      ctx.fillStyle = 'rgba(5, 6, 15, 0.22)';
      ctx.fillRect(0, 0, W, H);

      ctx.globalCompositeOperation = 'lighter';

      const cx = W * 0.48;
      const cy = H * 0.52;

      // Render Warp Stars
      for (const s of warpStars) {
        s.z -= s.speed;
        if (s.z <= 0) {
          s.z = 1000;
          s.x = (Math.random() - 0.5) * W;
          s.y = (Math.random() - 0.5) * H;
        }

        const scale = 1000 / s.z;
        const x = cx + s.x * scale;
        const y = cy + s.y * scale;

        const dist = Math.hypot(x - cx, y - cy);
        const maxDist = Math.hypot(W, H);
        const normDist = Math.min(dist / maxDist, 1);

        const streakLen = normDist * normDist * 200 + 10;
        const prevX = x - Math.cos(s.angle) * streakLen;
        const prevY = y - Math.sin(s.angle) * streakLen;

        const a = Math.min(normDist * normDist * 1.5, 1.0);
        const [cr, cg, cb] = s.col;

        const grad = ctx.createLinearGradient(prevX, prevY, x, y);
        grad.addColorStop(0, `rgba(${cr},${cg},${cb},0)`);
        grad.addColorStop(0.6, `rgba(${cr},${cg},${cb},${a * 0.4})`);
        grad.addColorStop(1, `rgba(255,255,255,${a})`);

        ctx.strokeStyle = grad;
        ctx.lineWidth = Math.max(scale * 1.5, 0.5);
        ctx.beginPath();
        ctx.moveTo(prevX, prevY);
        ctx.lineTo(x, y);
        ctx.stroke();
      }

      // Render Comets
      for (let i = 0; i < comets.length; i++) {
        const c = comets[i];
        c.x += c.vx;
        c.y += c.vy;
        c.life++;

        if (c.life > c.maxLife || c.x < -100 || c.x > W + 100 || c.y < -100 || c.y > H + 100) {
          comets[i] = spawnComet();
          continue;
        }

        const progress = c.life / c.maxLife;
        const fade = Math.sin(progress * Math.PI);
        const [cr, cg, cb] = c.col;

        const tailX = c.x - c.vx * 4;
        const tailY = c.y - c.vy * 4;

        const grad = ctx.createLinearGradient(tailX, tailY, c.x, c.y);
        grad.addColorStop(0, `rgba(${cr},${cg},${cb},0)`);
        grad.addColorStop(0.8, `rgba(${cr},${cg},${cb},${fade * 0.8})`);
        grad.addColorStop(1, `rgba(255,255,255,${fade})`);

        ctx.strokeStyle = grad;
        ctx.lineWidth = c.size;
        ctx.lineCap = 'round';
        ctx.beginPath();
        ctx.moveTo(tailX, tailY);
        ctx.lineTo(c.x, c.y);
        ctx.stroke();

        ctx.beginPath();
        ctx.fillStyle = `rgba(${cr},${cg},${cb},${fade * 0.3})`;
        ctx.arc(c.x, c.y, c.size * 3, 0, Math.PI * 2);
        ctx.fill();
      }

      ctx.globalCompositeOperation = 'source-over';

      // Render Asteroids
      ctx.strokeStyle = 'rgba(103,232,249,0.15)';
      for (let i = 0; i < asteroids.length; i++) {
        const a = asteroids[i];
        a.x += a.vx;
        a.y += a.vy;
        a.rot += a.vRot;

        if (a.x < -100 || a.x > W + 100 || a.y < -100 || a.y > H + 100) {
          asteroids[i] = spawnAsteroid();
          continue;
        }

        ctx.save();
        ctx.translate(a.x, a.y);
        ctx.rotate(a.rot);
        ctx.beginPath();
        for (let j = 0; j < a.pts.length; j++) {
          const angle = (j / a.pts.length) * Math.PI * 2;
          const r = a.size * a.pts[j];
          const px = Math.cos(angle) * r;
          const py = Math.sin(angle) * r;
          if (j === 0) ctx.moveTo(px, py);
          else ctx.lineTo(px, py);
        }
        ctx.closePath();
        ctx.fillStyle = 'rgba(10, 12, 30, 0.4)';
        ctx.fill();
        ctx.stroke();
        ctx.restore();
      }

      // Render Dust
      ctx.fillStyle = 'rgba(255,255,255,0.4)';
      for (let i = 0; i < dusts.length; i++) {
        const d = dusts[i];
        d.x += d.vx;
        d.y += d.vy;
        d.life++;

        if (d.life > d.maxLife || d.x < 0 || d.x > W || d.y < 0 || d.y > H) {
          dusts[i] = spawnDust();
          continue;
        }

        const fade = Math.sin((d.life / d.maxLife) * Math.PI);
        ctx.globalAlpha = fade * 0.5;
        ctx.beginPath();
        ctx.arc(d.x, d.y, 0.8, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.globalAlpha = 1.0;

      raf = requestAnimationFrame(render);
    };

    raf = requestAnimationFrame(render);

    return () => {
      cancelAnimationFrame(raf);
      resizeObserver.disconnect();
    };
  }, []);

  return (
    <div
      className="absolute left-0 bottom-0 pointer-events-none z-[2] overflow-hidden"
      style={{
        width: "56vw",
        height: "62vh",
        WebkitMaskImage: "radial-gradient(ellipse 88% 88% at 18% 82%, black 0%, transparent 100%)",
        maskImage: "radial-gradient(ellipse 88% 88% at 18% 82%, black 0%, transparent 100%)",
      }}
    >
      <canvas ref={canvasRef} className="absolute inset-0 h-full w-full" />
    </div>
  );
}
